name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true

    - name: Check if version has changed
      id: check
      run: |
        PKG_VERSION=$(node -p "require('./package.json').version")
        NPM_VERSION=$(npm view s2polyline-ts version 2>/dev/null || echo "0.0.0")
        if [ "$PKG_VERSION" != "$NPM_VERSION" ]; then
          echo "::set-output name=should_publish::true"
        fi

    - name: Publish to NPM
      if: steps.check.outputs.should_publish == 'true' && github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
